upgrade_commands:
  default:
    - ./vendor/bin/drush state:set system.maintenance_mode 1 --input-format=integer --yes
    - touch disable-config-readonly
    - ./vendor/bin/run redis:flush-all
    - ./vendor/bin/drush updatedb --no-post-updates --yes
    - ./vendor/bin/drush config:import --yes
    - ./vendor/bin/drush updatedb --yes
    - rm disable-config-readonly
    - ./vendor/bin/drush state:set system.maintenance_mode 0 --input-format=integer --yes
