version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.1
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html:delegated # Non Mac users.
# - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      # ASDA credentials.
      # By leaving these variables empty Docker Compose will set them to their
      # host values.
      ASDA_USER:
      ASDA_PASSWORD:
      # XDEBUG CONFIGURATION
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
    env_file:
      - .env
      - .env.local
  mysql:
#    image: percona:5
    image: percona/percona-server:5.7
    volumes:
      - ./resources/docker/mysql/config:/etc/mysql/conf.d:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  virtuoso:
    image: tenforce/virtuoso
    environment:
      - SPARQL_UPDATE=true
      # Virtuoso .ini overrides. Pattern: VIRT_$SECTION_$KEY=$VALUE
      # See https://hub.docker.com/r/tenforce/virtuoso
      - VIRT_Parameters_O_DIRECT=1
      - VIRT_Parameters_ThreadCleanupInterval=1
      - VIRT_Parameters_NumberOfBuffers=340000
      - VIRT_Parameters_MaxDirtyBuffers=250000
      - VIRT_Replication_ServerEnable=0
      - VIRT_SPARQL_ResultSetMaxRows=1000000

    volumes:
      - ./data/virtuoso:/data:delegated
    ports:
      - 8890:8890

  solr:
    image: solr:6
    ports:
      - 8983:8983
    volumes:
      - ./data/solr:/var/solr:delegated
      - ./web/modules/contrib/search_api_solr/solr-conf/6.x:/solr-conf:delegated
    entrypoint:
      - docker-entrypoint.sh
      - bash
      - '-c'
      - 'mkdir -p /opt/docker-solr/drupal/conf; cp -r /solr-conf/* /opt/docker-solr/drupal/conf/; sed -i "/solr.install.dir=/c\solr.install.dir=/opt/solr" /opt/docker-solr/drupal/conf/solrcore.properties; precreate-core drupal_published /opt/docker-solr/drupal; precreate-core drupal_unpublished /opt/docker-solr/drupal; exec solr -f'

  redis:
    image: redis:5
    ports:
      - 6379:6379

  # Spawn a Selenium server, including also a VNC server on localhost:5900 (the
  # password is "secret")
  selenium:
    image: selenium/standalone-chrome-debug:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - 5900:5900
    expose:
      - 4444

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing. You can find more information about Docker for Mac here: https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos

#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"

#### End Mac users.